### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by sahilpohare** [tronprotocol/tron-studio#11]
Exception in Application start method
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtil                                                                                         s$2 (file:/E:/TRONPROTOCOLDIRECTORIES/tron-studio/build/libs/TronStudio.jar) to                                                                                          method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.se                                                                                         curity.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframewor                                                                                         k.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect                                                                                         ive access operations
WARNING: All illegal access operations will be denied in a future release
javax.xml.transform.TransformerException: java.io.FileNotFoundException: C:\User                                                                                         s\Sahil\TronStudio\record\network.xml (The system cannot find the path specified                                                                                         )
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl                                                                                         .getOutputHandler(Unknown Source)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl                                                                                         .transform(Unknown Source)
        at org.tron.studio.MainApplication.writeIntoXML(MainApplication.java:110                                                                                         )
        at org.tron.studio.MainApplication.stop(MainApplication.java:123)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launch                                                                                         Application1$10(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAnd                                                                                         Wait$11(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLat                                                                                         er$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLat                                                                                         er$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unk                                                                                         nown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native M                                                                                         ethod)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(                                                                                         Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\Users\Sahil\TronStudio\record\netwo                                                                                         rk.xml (The system cannot find the path specified)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        ... 13 more
---------
java.io.FileNotFoundException: C:\Users\Sahil\TronStudio\record\network.xml (The                                                                                          system cannot find the path specified)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl                                                                                         .getOutputHandler(Unknown Source)
        at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl                                                                                         .transform(Unknown Source)
        at org.tron.studio.MainApplication.writeIntoXML(MainApplication.java:110                                                                                         )
        at org.tron.studio.MainApplication.stop(MainApplication.java:123)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launch                                                                                         Application1$10(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAnd                                                                                         Wait$11(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLat                                                                                         er$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLat                                                                                         er$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unk                                                                                         nown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native M                                                                                         ethod)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(                                                                                         Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in Application stop method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ                                                                                         e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow                                                                                         n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un                                                                                         known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplica                                                                                         tionWithArgs(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplica                                                                                         tion(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ                                                                                         e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow                                                                                         n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un                                                                                         known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplica                                                                                         tion1(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launch                                                                                         Application$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/StyleConverterImpl
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown                                                                                          Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPath                                                                                         OrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unkn                                                                                         own Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown So                                                                                         urce)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(U                                                                                         nknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at com.jfoenix.controls.JFXButton$StyleableProperties.<clinit>(JFXButton                                                                                         .java:208)
        at com.jfoenix.controls.JFXButton.<init>(JFXButton.java:156)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInsta                                                                                         nce0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInsta                                                                                         nce(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newI                                                                                         nstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constru                                                                                         ctValue(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(U                                                                                         nknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(Unknown Source                                                                                         )
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.access$2700(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$IncludeElement.constructValue(Unkn                                                                                         own Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(U                                                                                         nknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(Unknown Source                                                                                         )
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(Unknown Source)
        at org.tron.studio.MainApplication.start(MainApplication.java:144)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launch                                                                                         Application1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAnd                                                                                         Wait$11(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLat                                                                                         er$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLat                                                                                         er$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unk                                                                                         nown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native M                                                     ethod)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(                                                                                         Unknown Source)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.StyleConverterIm                                                                                         pl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown So                                                                                         urce)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(U                                                                                         nknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 43 more
Exception running application org.tron.studio.MainApplication

**Comment by UnforgivenZZZ** [comment]
the network.xml saved your network environment preferences. try manually create C:\Users\Sahil\TronStudio\record\network.xml

**Comment by tycm4109** [comment]
@sahilpohare  Hi, did that advice help you solve your issue? Please join us in the TRON Developers Discord channel at https://discordapp.com/invite/GsRgsTD.

**Comment by sahilpohare** [comment]
@tmao1129 It still doesn't work

**Comment by sahilpohare** [comment]
``C:\Users\Sahil>java -jar TronStudio.jar
Exception in Application start method
File saved!
Exception in Application stop method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/StyleConverterImpl
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at com.jfoenix.controls.JFXButton$StyleableProperties.<clinit>(JFXButton.java:208)
        at com.jfoenix.controls.JFXButton.<init>(JFXButton.java:156)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.access$2700(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$IncludeElement.constructValue(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(Unknown Source)
        at org.tron.studio.MainApplication.start(MainApplication.java:144)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.StyleConverterImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 43 more this is the new error``
